"""add_invitations

Revision ID: ef6d83ef1c5c
Revises: 1af323f0d31b
Create Date: 2020-11-15 11:34:51.457018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d83ef1c5c'
down_revision = '1af323f0d31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text()),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('bands_name_key', 'bands', type_='unique')
    op.create_unique_constraint("unique_name_per_owner", 'bands', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_name_per_owner", 'bands', type_='unique')
    op.create_unique_constraint('bands_name_key', 'bands', ['name'])
    op.drop_table('invitations')
    # ### end Alembic commands ###
