"""add_bands

Revision ID: 170e76e9ed46
Revises: 5f9eeaac428b
Create Date: 2020-11-11 18:11:38.228439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170e76e9ed46'
down_revision = '5f9eeaac428b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('isPublic', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band')
    # ### end Alembic commands ###
